apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app.kubernetes.io/name: conductor-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: conductor-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-router
  labels:
    app.kubernetes.io/name: conductor-router
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: conductor-router
    app.kubernetes.io/instance: {{ .Release.Name }}
